import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import { ServerStatusProvider } from "../context/ServerStatusContext";
import { ServerOfflineOverlay } from "../components/layout/ServerOfflineOverlay";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Proyekto",
  description: "Generated by create next app",
  icons: {
    icon: "/proyekto.png",
    apple: "/proyekto.png",
    shortcut: "/proyekto.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <ServerStatusProvider>
          <ServerOfflineOverlay />
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            <Providers>
              {children}
              <Toaster position="top-right" theme="dark" />
            </Providers>
          </ThemeProvider>
        </ServerStatusProvider>
      </body>
    </html>
  );
}
